package ds.s.model;

import java.util.Date;

public class Device {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device.id
     *
     * @mbggenerated Mon Nov 25 22:35:00 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device.user_id
     *
     * @mbggenerated Mon Nov 25 22:35:00 CST 2013
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device.imei
     *
     * @mbggenerated Mon Nov 25 22:35:00 CST 2013
     */
    private String imei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device.created_time
     *
     * @mbggenerated Mon Nov 25 22:35:00 CST 2013
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device.deleted
     *
     * @mbggenerated Mon Nov 25 22:35:00 CST 2013
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device.version
     *
     * @mbggenerated Mon Nov 25 22:35:00 CST 2013
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device.id
     *
     * @return the value of t_device.id
     *
     * @mbggenerated Mon Nov 25 22:35:00 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device.id
     *
     * @param id the value for t_device.id
     *
     * @mbggenerated Mon Nov 25 22:35:00 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device.user_id
     *
     * @return the value of t_device.user_id
     *
     * @mbggenerated Mon Nov 25 22:35:00 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device.user_id
     *
     * @param userId the value for t_device.user_id
     *
     * @mbggenerated Mon Nov 25 22:35:00 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device.imei
     *
     * @return the value of t_device.imei
     *
     * @mbggenerated Mon Nov 25 22:35:00 CST 2013
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device.imei
     *
     * @param imei the value for t_device.imei
     *
     * @mbggenerated Mon Nov 25 22:35:00 CST 2013
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device.created_time
     *
     * @return the value of t_device.created_time
     *
     * @mbggenerated Mon Nov 25 22:35:00 CST 2013
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device.created_time
     *
     * @param createdTime the value for t_device.created_time
     *
     * @mbggenerated Mon Nov 25 22:35:00 CST 2013
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device.deleted
     *
     * @return the value of t_device.deleted
     *
     * @mbggenerated Mon Nov 25 22:35:00 CST 2013
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device.deleted
     *
     * @param deleted the value for t_device.deleted
     *
     * @mbggenerated Mon Nov 25 22:35:00 CST 2013
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device.version
     *
     * @return the value of t_device.version
     *
     * @mbggenerated Mon Nov 25 22:35:00 CST 2013
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device.version
     *
     * @param version the value for t_device.version
     *
     * @mbggenerated Mon Nov 25 22:35:00 CST 2013
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}