package ds.s.model;

import java.util.Date;

public class Share {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_share.id
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_share.user_id
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_share.image_id
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    private Integer imageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_share.content
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_share.created_time
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_share.updated_time
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_share.deleted
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_share.version
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_share.id
     *
     * @return the value of t_share.id
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_share.id
     *
     * @param id the value for t_share.id
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_share.user_id
     *
     * @return the value of t_share.user_id
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_share.user_id
     *
     * @param userId the value for t_share.user_id
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_share.image_id
     *
     * @return the value of t_share.image_id
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    public Integer getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_share.image_id
     *
     * @param imageId the value for t_share.image_id
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_share.content
     *
     * @return the value of t_share.content
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_share.content
     *
     * @param content the value for t_share.content
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_share.created_time
     *
     * @return the value of t_share.created_time
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_share.created_time
     *
     * @param createdTime the value for t_share.created_time
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_share.updated_time
     *
     * @return the value of t_share.updated_time
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_share.updated_time
     *
     * @param updatedTime the value for t_share.updated_time
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_share.deleted
     *
     * @return the value of t_share.deleted
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_share.deleted
     *
     * @param deleted the value for t_share.deleted
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_share.version
     *
     * @return the value of t_share.version
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_share.version
     *
     * @param version the value for t_share.version
     *
     * @mbggenerated Sun Dec 01 14:52:49 CST 2013
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}