package ds.s.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.id
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.device_id
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    private Integer deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.nickname
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.readme
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    private String readme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.created_time
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.updated_time
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.deleted
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.version
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.id
     *
     * @return the value of t_users.id
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.id
     *
     * @param id the value for t_users.id
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.device_id
     *
     * @return the value of t_users.device_id
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.device_id
     *
     * @param deviceId the value for t_users.device_id
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.nickname
     *
     * @return the value of t_users.nickname
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.nickname
     *
     * @param nickname the value for t_users.nickname
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.readme
     *
     * @return the value of t_users.readme
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    public String getReadme() {
        return readme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.readme
     *
     * @param readme the value for t_users.readme
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    public void setReadme(String readme) {
        this.readme = readme == null ? null : readme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.created_time
     *
     * @return the value of t_users.created_time
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.created_time
     *
     * @param createdTime the value for t_users.created_time
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.updated_time
     *
     * @return the value of t_users.updated_time
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.updated_time
     *
     * @param updatedTime the value for t_users.updated_time
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.deleted
     *
     * @return the value of t_users.deleted
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.deleted
     *
     * @param deleted the value for t_users.deleted
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.version
     *
     * @return the value of t_users.version
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.version
     *
     * @param version the value for t_users.version
     *
     * @mbggenerated Mon Nov 25 22:16:35 CST 2013
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}