package ds.s.mapper;

import ds.s.model.Device;
import ds.s.model.DeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ds_devices
     *
     * @mbggenerated Sun Nov 24 18:52:24 CST 2013
     */
    int countByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ds_devices
     *
     * @mbggenerated Sun Nov 24 18:52:24 CST 2013
     */
    int deleteByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ds_devices
     *
     * @mbggenerated Sun Nov 24 18:52:24 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ds_devices
     *
     * @mbggenerated Sun Nov 24 18:52:24 CST 2013
     */
    int insert(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ds_devices
     *
     * @mbggenerated Sun Nov 24 18:52:24 CST 2013
     */
    int insertSelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ds_devices
     *
     * @mbggenerated Sun Nov 24 18:52:24 CST 2013
     */
    List<Device> selectByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ds_devices
     *
     * @mbggenerated Sun Nov 24 18:52:24 CST 2013
     */
    Device selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ds_devices
     *
     * @mbggenerated Sun Nov 24 18:52:24 CST 2013
     */
    int updateByExampleSelective(@Param("record") Device record, @Param("example") DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ds_devices
     *
     * @mbggenerated Sun Nov 24 18:52:24 CST 2013
     */
    int updateByExample(@Param("record") Device record, @Param("example") DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ds_devices
     *
     * @mbggenerated Sun Nov 24 18:52:24 CST 2013
     */
    int updateByPrimaryKeySelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ds_devices
     *
     * @mbggenerated Sun Nov 24 18:52:24 CST 2013
     */
    int updateByPrimaryKey(Device record);
}