package ds.s.mapper;

import ds.s.model.Share;
import ds.s.model.ShareExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share
     *
     * @mbggenerated Mon Nov 25 22:59:12 CST 2013
     */
    int countByExample(ShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share
     *
     * @mbggenerated Mon Nov 25 22:59:12 CST 2013
     */
    int deleteByExample(ShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share
     *
     * @mbggenerated Mon Nov 25 22:59:12 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share
     *
     * @mbggenerated Mon Nov 25 22:59:12 CST 2013
     */
    int insert(Share record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share
     *
     * @mbggenerated Mon Nov 25 22:59:12 CST 2013
     */
    int insertSelective(Share record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share
     *
     * @mbggenerated Mon Nov 25 22:59:12 CST 2013
     */
    List<Share> selectByExample(ShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share
     *
     * @mbggenerated Mon Nov 25 22:59:12 CST 2013
     */
    Share selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share
     *
     * @mbggenerated Mon Nov 25 22:59:12 CST 2013
     */
    int updateByExampleSelective(@Param("record") Share record, @Param("example") ShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share
     *
     * @mbggenerated Mon Nov 25 22:59:12 CST 2013
     */
    int updateByExample(@Param("record") Share record, @Param("example") ShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share
     *
     * @mbggenerated Mon Nov 25 22:59:12 CST 2013
     */
    int updateByPrimaryKeySelective(Share record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share
     *
     * @mbggenerated Mon Nov 25 22:59:12 CST 2013
     */
    int updateByPrimaryKey(Share record);
}